services:
  api-catalog:
    image: adschosen/api-catalog:1.0.0
    container_name: api-catalog
    ports:
      - 6070:6070
    restart: always
    links:
      - api-catalog-db

  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3310:3306

  api-clusters:
    image: adschosen/api-clusters:1.0.0
    container_name: api-clusters
    ports:
      - 4070:4070
    restart: always
    links:
      - api-clusters-db

  api-clusters-db:
    container_name: api-clusters-db
    image: redis:alpine
    restart: always
    ports:
      - 6079:6379

  api-itineraries-search:
    image: adschosen/api-itineraries-search:1.0.0
    container_name: api-itineraries-search
    ports:
      - 7070:7070
    restart: always

  api-pricing:
    image: adschosen/api-pricing:1.0.0
    container_name: api-pricing
    ports:
      - 5070:5070
    restart: always

  api-pricing-db:
    container_name: api-pricing-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_pricing'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3311:3306

  api-provider-alpha:
    image: adschosen/api-provider-alpha:1.0.0
    container_name: api-provider-alpha
    ports:
      - 8070:8070
    restart: always

  api-provider-beta:
    image: adschosen/api-provider-beta:1.0.0
    container_name: api-provider-beta
    ports:
      - 9070:9070
    restart: always

  api-reservations:
    image: adschosen/api-reservations-mongo:1.0.0
    container_name: api-reservations
    ports:
      - 3070:3070
    restart: always
    links:
      - api-reservation-db

  api-reservation-db:
    image: mongo:5
    container_name: api-reservation-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: reservations
    ports:
      - 5079:27017

  api-reservation-db-rest:
    image: softinstigate/restheart:6.3.3
    ports:
      - 8082:8080
    volumes:
      - ./docker/restheart:/opt/restheart/etc
    depends_on:
      - api-reservation-db
